import { Provider } from './components/provider/Provider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJs Authentication ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body data-theme="dark" className={inter.className}>
      <Provider>
      {children}
      </Provider>
      </body>
    </html>
  )
}
